[build]
  publish = "dist"
  command = "yarn build"
[[headers]]
  for = "*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'none'"
[[headers]]
  for = "*.(css|ico|mp3|png|svg)"
  [headers.values]
    Cache-Control = "public,max-age=31536000,immutable"
[[headers]]
  for = "index.js"
  [headers.values]
    Cache-Control = "public,max-age=31536000,immutable"
[[redirects]]
  from = "*"
  status = 200
  to = "/"
